# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vk/Games/ogre3d/advanced-ogre-framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vk/Games/ogre3d/advanced-ogre-framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vk/Games/ogre3d/advanced-ogre-framework/CMakeFiles /home/vk/Games/ogre3d/advanced-ogre-framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vk/Games/ogre3d/advanced-ogre-framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OgreApp

# Build rule for target.
OgreApp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreApp
.PHONY : OgreApp

# fast build rule for target.
OgreApp/fast:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/build
.PHONY : OgreApp/fast

AdvancedOgreFramework.o: AdvancedOgreFramework.cpp.o
.PHONY : AdvancedOgreFramework.o

# target to build an object file
AdvancedOgreFramework.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/AdvancedOgreFramework.cpp.o
.PHONY : AdvancedOgreFramework.cpp.o

AdvancedOgreFramework.i: AdvancedOgreFramework.cpp.i
.PHONY : AdvancedOgreFramework.i

# target to preprocess a source file
AdvancedOgreFramework.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/AdvancedOgreFramework.cpp.i
.PHONY : AdvancedOgreFramework.cpp.i

AdvancedOgreFramework.s: AdvancedOgreFramework.cpp.s
.PHONY : AdvancedOgreFramework.s

# target to generate assembly for a file
AdvancedOgreFramework.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/AdvancedOgreFramework.cpp.s
.PHONY : AdvancedOgreFramework.cpp.s

AppStateManager.o: AppStateManager.cpp.o
.PHONY : AppStateManager.o

# target to build an object file
AppStateManager.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/AppStateManager.cpp.o
.PHONY : AppStateManager.cpp.o

AppStateManager.i: AppStateManager.cpp.i
.PHONY : AppStateManager.i

# target to preprocess a source file
AppStateManager.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/AppStateManager.cpp.i
.PHONY : AppStateManager.cpp.i

AppStateManager.s: AppStateManager.cpp.s
.PHONY : AppStateManager.s

# target to generate assembly for a file
AppStateManager.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/AppStateManager.cpp.s
.PHONY : AppStateManager.cpp.s

BaseNpc.o: BaseNpc.cpp.o
.PHONY : BaseNpc.o

# target to build an object file
BaseNpc.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/BaseNpc.cpp.o
.PHONY : BaseNpc.cpp.o

BaseNpc.i: BaseNpc.cpp.i
.PHONY : BaseNpc.i

# target to preprocess a source file
BaseNpc.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/BaseNpc.cpp.i
.PHONY : BaseNpc.cpp.i

BaseNpc.s: BaseNpc.cpp.s
.PHONY : BaseNpc.s

# target to generate assembly for a file
BaseNpc.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/BaseNpc.cpp.s
.PHONY : BaseNpc.cpp.s

DemoApp.o: DemoApp.cpp.o
.PHONY : DemoApp.o

# target to build an object file
DemoApp.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/DemoApp.cpp.o
.PHONY : DemoApp.cpp.o

DemoApp.i: DemoApp.cpp.i
.PHONY : DemoApp.i

# target to preprocess a source file
DemoApp.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/DemoApp.cpp.i
.PHONY : DemoApp.cpp.i

DemoApp.s: DemoApp.cpp.s
.PHONY : DemoApp.s

# target to generate assembly for a file
DemoApp.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/DemoApp.cpp.s
.PHONY : DemoApp.cpp.s

DotSceneLoader.o: DotSceneLoader.cpp.o
.PHONY : DotSceneLoader.o

# target to build an object file
DotSceneLoader.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/DotSceneLoader.cpp.o
.PHONY : DotSceneLoader.cpp.o

DotSceneLoader.i: DotSceneLoader.cpp.i
.PHONY : DotSceneLoader.i

# target to preprocess a source file
DotSceneLoader.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/DotSceneLoader.cpp.i
.PHONY : DotSceneLoader.cpp.i

DotSceneLoader.s: DotSceneLoader.cpp.s
.PHONY : DotSceneLoader.s

# target to generate assembly for a file
DotSceneLoader.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/DotSceneLoader.cpp.s
.PHONY : DotSceneLoader.cpp.s

GameState.o: GameState.cpp.o
.PHONY : GameState.o

# target to build an object file
GameState.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/GameState.cpp.o
.PHONY : GameState.cpp.o

GameState.i: GameState.cpp.i
.PHONY : GameState.i

# target to preprocess a source file
GameState.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/GameState.cpp.i
.PHONY : GameState.cpp.i

GameState.s: GameState.cpp.s
.PHONY : GameState.s

# target to generate assembly for a file
GameState.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/GameState.cpp.s
.PHONY : GameState.cpp.s

MenuState.o: MenuState.cpp.o
.PHONY : MenuState.o

# target to build an object file
MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/MenuState.cpp.o
.PHONY : MenuState.cpp.o

MenuState.i: MenuState.cpp.i
.PHONY : MenuState.i

# target to preprocess a source file
MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/MenuState.cpp.i
.PHONY : MenuState.cpp.i

MenuState.s: MenuState.cpp.s
.PHONY : MenuState.s

# target to generate assembly for a file
MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/MenuState.cpp.s
.PHONY : MenuState.cpp.s

NpcOwnedStates.o: NpcOwnedStates.cpp.o
.PHONY : NpcOwnedStates.o

# target to build an object file
NpcOwnedStates.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/NpcOwnedStates.cpp.o
.PHONY : NpcOwnedStates.cpp.o

NpcOwnedStates.i: NpcOwnedStates.cpp.i
.PHONY : NpcOwnedStates.i

# target to preprocess a source file
NpcOwnedStates.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/NpcOwnedStates.cpp.i
.PHONY : NpcOwnedStates.cpp.i

NpcOwnedStates.s: NpcOwnedStates.cpp.s
.PHONY : NpcOwnedStates.s

# target to generate assembly for a file
NpcOwnedStates.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/NpcOwnedStates.cpp.s
.PHONY : NpcOwnedStates.cpp.s

PauseState.o: PauseState.cpp.o
.PHONY : PauseState.o

# target to build an object file
PauseState.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/PauseState.cpp.o
.PHONY : PauseState.cpp.o

PauseState.i: PauseState.cpp.i
.PHONY : PauseState.i

# target to preprocess a source file
PauseState.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/PauseState.cpp.i
.PHONY : PauseState.cpp.i

PauseState.s: PauseState.cpp.s
.PHONY : PauseState.s

# target to generate assembly for a file
PauseState.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/PauseState.cpp.s
.PHONY : PauseState.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... OgreApp"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AdvancedOgreFramework.o"
	@echo "... AdvancedOgreFramework.i"
	@echo "... AdvancedOgreFramework.s"
	@echo "... AppStateManager.o"
	@echo "... AppStateManager.i"
	@echo "... AppStateManager.s"
	@echo "... BaseNpc.o"
	@echo "... BaseNpc.i"
	@echo "... BaseNpc.s"
	@echo "... DemoApp.o"
	@echo "... DemoApp.i"
	@echo "... DemoApp.s"
	@echo "... DotSceneLoader.o"
	@echo "... DotSceneLoader.i"
	@echo "... DotSceneLoader.s"
	@echo "... GameState.o"
	@echo "... GameState.i"
	@echo "... GameState.s"
	@echo "... MenuState.o"
	@echo "... MenuState.i"
	@echo "... MenuState.s"
	@echo "... NpcOwnedStates.o"
	@echo "... NpcOwnedStates.i"
	@echo "... NpcOwnedStates.s"
	@echo "... PauseState.o"
	@echo "... PauseState.i"
	@echo "... PauseState.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

